'Patenga Hub') THEN '3PL' ELSE "DestinationHub" END AS "DestinationHub",
	"ShopName",
	"SellerCode" AS "SellerShortCode",
	CASE WHEN "CustomerStatus" IN ('Delivered') OR "DeliveredDate" IS NOT NULL THEN 'Delivered' ELSE "CustomerStatus" END AS "OrderStatus",
	"LastUpdated",
	"DeliveredDate",
	"ReturnUpdatedDate",
	"SellerId",
	"ShopSKU",
	"CategoryId" AS "DeepcatID",
	"ProductName",
	"Vertical",
	"cat1",
    "cat2",
    "cat3",
    "cat4",
    "cat5",
    "cat6",
    "deepestcategory",
    "IsConsignmentSku",
	"SellingPrice",
	"Quantity",
	"TotalPrice",
	"OrderValue",
	COALESCE("TransactionAmount","OrderValue") AS "PaidPrice",
	"DiscountAmount",
	"IsQC" AS "ReturnQC",
	"ReturnStatus",
	"IsFailedDelivery",
	"FulfillmentBy",
	"CartupDiscount"+"SellerDiscount" AS "TotalDiscount",
	"CustomerShipping",
	"SellerShipping",
	"CartupShipping",
	"CartupDiscount",
	"SellerDiscount",
	"PaymentMethod",
	"TrxID",
	"ReturnQty",
	"CardNo",
	"ReturnQty"*"ItemPrice" AS "ReturnAmount",
	"EligibleForRefund"
FROM cartup_master
WHERE "OrderDate" < CURRENT_DATE
AND ("PaymentMethod" IS NOT NULL OR "IsPaid" IS TRUE)
ORDER BY 
	"OrderDate", "CustomerOrderCode"
